version: "3"
services:
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.6
    command: mysqld --sql-mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=tcudb
      - MYSQL_PASSWORD=TsDu9nR1vVrl
      - MYSQL_DATABASE=magento
    ports:
      - "3308:3306"
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=magento
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/data:/app/src
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - mariadb
      - mysql
  nginx_store:
    image: nginx:1.13
    volumes:
      - ./src:/app/src
      - ./docker/nginx/vhost/store.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - app
  app:
    build: .
    env_file: ./docker/environments/development.env.dist
    volumes:
      - ./src:/app/src
    links:
      - mysql
      - redis
    tty: true
    ports:
      - 9000
networks:
  default:
    driver: bridge
